/**
 * VIEW LAYER - MyDocuments.jsx
 * 
 * Responsibility: Display user's previously generated documents
 * 
 * Architecture:
 * - This is a View component (MVC pattern)
 * - Fetches data using documentService (service layer)
 * - Displays documents in a user-friendly list
 * - Handles loading and error states
 * 
 * Features:
 * - Lists all documents generated by the user
 * - Shows document type, creation date, and preview
 * - Click to view full document
 * - Shows "No documents yet" state when empty
 * - Loading state while fetching data
 */

import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import {
  Container,
  Typography,
  Box,
  Card,
  CardContent,
  CardActions,
  Button,
  CircularProgress,
  Alert,
  Stack,
  Chip,
  Divider,
} from '@mui/material';
import DescriptionIcon from '@mui/icons-material/Description';
import CalendarTodayIcon from '@mui/icons-material/CalendarToday';
import VisibilityIcon from '@mui/icons-material/Visibility';
import { useAuth } from '../AuthContext';
import { getUserDocuments } from '../services/documentService';
import '../styles/MyDocuments.css';

const MyDocuments = () => {
  const { user } = useAuth();
  const navigate = useNavigate();
  const [documents, setDocuments] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  // Fetch user's documents when component loads
  useEffect(() => {
    const fetchDocuments = async () => {
      try {
        setLoading(true);
        setError(null);
        
        // Call service to fetch documents from backend
        // Works with or without Firebase authentication (demo mode)
        const userDocs = await getUserDocuments();
        setDocuments(userDocs);
      } catch (err) {
        console.error('Error fetching documents:', err);
        setError(err.message || 'Failed to load documents. Please try again.');
      } finally {
        setLoading(false);
      }
    };

    fetchDocuments();
  }, [user]);

  // Format date for display
  const formatDate = (dateString) => {
    const date = new Date(dateString);
    return date.toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    });
  };

  // Get preview snippet (first 150 characters)
  const getPreview = (content) => {
    if (!content) return 'No content available';
    const preview = content.substring(0, 150);
    return preview.length < content.length ? preview + '...' : preview;
  };

  // Format document type for display
  const formatDocumentType = (type) => {
    return type
      .split('-')
      .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
      .join(' ');
  };

  // Handle view document click
  const handleViewDocument = (document) => {
    // Navigate to generated document view with document data
    navigate(`/documents/${document.documentType}/generated`, {
      state: {
        document: {
          title: formatDocumentType(document.documentType),
          content: document.content,
          type: document.documentType,
        },
        fromMyDocuments: true, // Flag to indicate coming from My Documents
      },
    });
  };

  // Note: In demo mode, documents can be viewed without authentication
  // All documents will show (they're all saved with demo-user ID)

  return (
    <Container maxWidth="lg" sx={{ py: 4 }}>
      {/* Header */}
      <Box sx={{ mb: 4 }}>
        <Typography variant="h4" component="h1" sx={{ fontWeight: 600, mb: 1 }}>
          My Documents
        </Typography>
        <Typography variant="body1" color="text.secondary">
          View and manage your previously generated legal documents
        </Typography>
      </Box>

      {/* Loading State */}
      {loading && (
        <Box sx={{ display: 'flex', justifyContent: 'center', py: 8 }}>
          <CircularProgress />
        </Box>
      )}

      {/* Error State */}
      {error && !loading && (
        <Alert severity="error" sx={{ mb: 3 }}>
          {error}
        </Alert>
      )}

      {/* Empty State */}
      {!loading && !error && documents.length === 0 && (
        <Card elevation={2} sx={{ p: 6, textAlign: 'center' }}>
          <DescriptionIcon sx={{ fontSize: 64, color: 'text.secondary', mb: 2 }} />
          <Typography variant="h6" color="text.secondary" gutterBottom>
            No documents yet
          </Typography>
          <Typography variant="body2" color="text.secondary" sx={{ mb: 3 }}>
            Start generating legal documents to see them here
          </Typography>
          <Button
            variant="contained"
            color="primary"
            onClick={() => navigate('/documents')}
          >
            Generate Your First Document
          </Button>
        </Card>
      )}

      {/* Documents List */}
      {!loading && !error && documents.length > 0 && (
        <Stack spacing={3}>
          <Typography variant="body2" color="text.secondary">
            {documents.length} {documents.length === 1 ? 'document' : 'documents'} found
          </Typography>

          {documents.map((doc) => (
            <Card key={doc.id} elevation={2} sx={{ '&:hover': { elevation: 4 } }}>
              <CardContent>
                <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'start', mb: 2 }}>
                  <Box>
                    <Typography variant="h6" component="h2" gutterBottom>
                      {formatDocumentType(doc.documentType)}
                    </Typography>
                    <Chip
                      label={doc.documentType}
                      size="small"
                      color="primary"
                      variant="outlined"
                      sx={{ mb: 1 }}
                    />
                  </Box>
                  <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, color: 'text.secondary' }}>
                    <CalendarTodayIcon fontSize="small" />
                    <Typography variant="caption">
                      {formatDate(doc.createdAt)}
                    </Typography>
                  </Box>
                </Box>

                <Divider sx={{ my: 2 }} />

                <Typography variant="body2" color="text.secondary" sx={{ fontFamily: 'monospace', whiteSpace: 'pre-wrap' }}>
                  {getPreview(doc.content)}
                </Typography>
              </CardContent>

              <CardActions sx={{ px: 2, pb: 2 }}>
                <Button
                  size="small"
                  variant="contained"
                  startIcon={<VisibilityIcon />}
                  onClick={() => handleViewDocument(doc)}
                >
                  View Full Document
                </Button>
              </CardActions>
            </Card>
          ))}
        </Stack>
      )}

      {/* Navigation */}
      <Box sx={{ mt: 4, display: 'flex', gap: 2 }}>
        <Button variant="outlined" onClick={() => navigate('/')}>
          ← Back to Home
        </Button>
        <Button variant="contained" onClick={() => navigate('/documents')}>
          Generate New Document
        </Button>
      </Box>
    </Container>
  );
};

export default MyDocuments;
